package uhc.uhcdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Appointment implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Type")
   private java.lang.String type;
   @org.kie.api.definition.type.Label(value = "Age From")
   private int agefrom;
   @org.kie.api.definition.type.Label(value = "Age To")
   private int ageto;
   @org.kie.api.definition.type.Label(value = "Gender")
   private java.lang.String gender;
   @org.kie.api.definition.type.Label(value = "Risk")
   private java.lang.String risk;
   @org.kie.api.definition.type.Label(value = "Patient Category")
   private java.lang.String patientcategory;
   @org.kie.api.definition.type.Label(value = "plan")
   private java.lang.String plan;
   @org.kie.api.definition.type.Label(value = "department")
   private java.lang.String department;
   @org.kie.api.definition.type.Label(value = "reason")
   private java.lang.String reason;
   @org.kie.api.definition.type.Label(value = "visittype")
   private java.lang.String visittype;
   @org.kie.api.definition.type.Label(value = "Is Scheduleable")
   private java.lang.Boolean schedule;

   public Appointment()
   {
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public int getAgefrom()
   {
      return this.agefrom;
   }

   public void setAgefrom(int agefrom)
   {
      this.agefrom = agefrom;
   }

   public int getAgeto()
   {
      return this.ageto;
   }

   public void setAgeto(int ageto)
   {
      this.ageto = ageto;
   }

   public java.lang.String getGender()
   {
      return this.gender;
   }

   public void setGender(java.lang.String gender)
   {
      this.gender = gender;
   }

   public java.lang.String getRisk()
   {
      return this.risk;
   }

   public void setRisk(java.lang.String risk)
   {
      this.risk = risk;
   }

   public java.lang.String getPatientcategory()
   {
      return this.patientcategory;
   }

   public void setPatientcategory(java.lang.String patientcategory)
   {
      this.patientcategory = patientcategory;
   }

   public java.lang.String getPlan()
   {
      return this.plan;
   }

   public void setPlan(java.lang.String plan)
   {
      this.plan = plan;
   }

   public java.lang.String getDepartment()
   {
      return this.department;
   }

   public void setDepartment(java.lang.String department)
   {
      this.department = department;
   }

   public java.lang.String getReason()
   {
      return this.reason;
   }

   public void setReason(java.lang.String reason)
   {
      this.reason = reason;
   }

   public java.lang.String getVisittype()
   {
      return this.visittype;
   }

   public void setVisittype(java.lang.String visittype)
   {
      this.visittype = visittype;
   }

   public java.lang.Boolean getSchedule()
   {
      return this.schedule;
   }

   public void setSchedule(java.lang.Boolean schedule)
   {
      this.schedule = schedule;
   }

   public Appointment(java.lang.String type, int agefrom, int ageto,
         java.lang.String gender, java.lang.String risk,
         java.lang.String patientcategory, java.lang.String plan,
         java.lang.String department, java.lang.String reason,
         java.lang.String visittype, java.lang.Boolean schedule)
   {
      this.type = type;
      this.agefrom = agefrom;
      this.ageto = ageto;
      this.gender = gender;
      this.risk = risk;
      this.patientcategory = patientcategory;
      this.plan = plan;
      this.department = department;
      this.reason = reason;
      this.visittype = visittype;
      this.schedule = schedule;
   }

}